### ISSUE TITLE
Add admin/GM briefing tab only

### ISSUE THREAD

**Issue by TheLocalPub** [EM-Creations/ArmA-3-Collection#3]
Reference 
https://github.com/TheLocalPub/Global-Conflicts-Framework-Stable/blob/fe9d3d3e7ed8101adb30ef644854ef7bb3be6d23/customization/briefing.sqf#L163

**Comment by EM-Creations** [comment]
Done, [here](https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/94) and [here](https://github.com/EM-Creations/ArmA-3-Collection/commit/0381090788361fd52919a23b70655a08820cfb0e).

Thanks to this I was able to also find out that the "Changelog" tab wasn't working :)
