### ISSUE TITLE
Bug: hasExtracted function returns nil

### ISSUE THREAD

**Issue by goosko** [EM-Creations/ArmA-3-Collection#4]
calling the
["VDV", "ExtractionAreaMarker", 0.9] call FUNC(hasExtracted);
And moving all units belonging to "VDV" team return nil, leading to a failure at the end condition.

**Comment by EM-Creations** [comment]
I will investigate.

**Comment by EM-Creations** [comment]
I've tested this with a marker, blufor unit and setting the ratio to 0.1 and after 1 minute of being in the extraction area it returns true. When testing this, are you testing with AI or players / yourself? `hasExtracted` calls [`BIS_fnc_listPlayers`](https://community.bistudio.com/wiki/BIS_fnc_listPlayers) to count, which I believe will only count units which are currently being played by a player.

**Comment by goosko** [comment]
Got it, I checked with AI. Closing this ticket.
