### ISSUE TITLE
Bug: kobold_ai_tasks do not work

### ISSUE THREAD

**Issue by goosko** [EM-Creations/ArmA-3-Collection#5]
Calling
`[_this, 4000] call KBAITSK_fnc_taskRush;`
on an AI squad synced to headless failed to work. They just stood around.

**Comment by EM-Creations** [comment]
I assume AI squad synced to PZAI headless? Does this work on the old framework?

**Comment by goosko** [comment]
Yes, there are numerous examples in the mission library.

AI squads synced to PZAI headless and the task is usually called on a waypoint activation. 
`[{[_this,1500] call kobld_ai_tasks_fnc_taskRush;},(group this),5] call CBA_fnc_waitAndExecute;`

**Comment by EM-Creations** [comment]
Should now be fixed here: https://github.com/Global-Conflicts-ArmA/Olsen-Framework-Arma-3/pull/91/commits/fee79af7043073c751fca40af6b9884c6355e4e1

Please reopen if not.
